version: 2

updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    target-branch: dev
    directory: /
    schedule:
      interval: weekly
    groups:
      node-production-dependencies:
        dependency-type: production
      node-development-dependencies:
        dependency-type: development
