name: Setup Python Environment
description: Configure python environment with project dependencies
inputs:
  python-version:
    description: The version to use in SemVer range syntax. See https://github.com/actions/setup-python/blob/main/README.md
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name: Install python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      with:
        python-version: ${{ inputs.python-version }}
        cache: poetry

    - name: Install project with dependencies
      run: poetry install
      shell: bash
