name: CI

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: "22"
  PYTHON_VERSION: "3.10"

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.dedupe.outputs.should_skip }}
      named: ${{ steps.dedupe.outputs.named }}
    steps:
      - name: Dedupe
        id: dedupe
        uses: lojoja/action-dedupe@main
        with:
          github_token: ${{ github.token }}
          paths: |
            - .github/workflows/CI.yml
          paths_named: |
            prettier:
              paths_ignore:
                - "**.lock"
                - .actrc
                - LICENSE
                - pnpm-lock.yaml
            tests_poetry:
              paths:
                - tests/poetry/**
            tests_uv:
              paths:
                - tests/uv/**

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).prettier.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run prettier
        uses: lojoja/action-prettier@main
        with:
          node_version: ${{ env.NODE_VERSION }}

  test-setup-python-env-poetry:
    name: Test setup-python-env poetry
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).tests_poetry.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run setup-python-env action
        id: action
        uses: ./
        with:
          working_directory: tests/poetry
          package_manager: poetry
          python_version: ${{ env.PYTHON_VERSION }}

  test-setup-python-env-uv:
    name: Test setup-python-env uv
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.should_skip == 'false' || ! fromJSON(needs.changes.outputs.named).tests_uv.should_skip
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run setup-python-env action
        id: action
        uses: ./
        with:
          working_directory: tests/uv
          package_manager: uv
          python_version: ${{ env.PYTHON_VERSION }}

  ci-result:
    name: CI Result
    runs-on: ubuntu-latest
    if: always()
    needs:
      - prettier
      - test-setup-python-env-poetry
      - test-setup-python-env-uv
    steps:
      - name: CI failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
      - name: CI passed
        run: exit 0
